# Generated by Django 4.2.6 on 2024-04-21 21:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(max_length=200)),
                ('end_date', models.DateTimeField(max_length=200)),
                ('book_id', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DENIED', 'DENIED'), ('APPROVED', 'APPROVED'), ('CANCELLED', 'CANCELLED'), ('TERMINATED', 'TERMINATED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('avaliable_to_give', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('genre', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
